const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"常见病症类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBingzheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"时间段管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShijianduan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"心理文章类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryWenzhang"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"常见病症管理",
                        "menuJump":"列表",
                        "tableName":"bingzheng"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"常见病症收藏管理",
                        "menuJump":"列表",
                        "tableName":"bingzhengCollection"
                    }
                ],
                "menu":"常见病症管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"心理文章管理",
                        "menuJump":"列表",
                        "tableName":"wenzhang"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"心理文章留言管理",
                        "menuJump":"列表",
                        "tableName":"wenzhangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"心理文章收藏管理",
                        "menuJump":"列表",
                        "tableName":"wenzhangCollection"
                    }
                ],
                "menu":"心理文章管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"咨询师管理",
                        "menuJump":"列表",
                        "tableName":"zixunshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"咨询师留言管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"咨询师收藏管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"咨询师订单管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiOrder"
                    }
                ],
                "menu":"咨询师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"咨询师留言管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiLiuyan"
                    }
                ],
                "menu":"咨询师留言管理"
            }
            ,
            {
                "child":[
                    {
                        "buttons":[
                            "订单",
                            "查看"
                        ],
                        "menu":"咨询师订单管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiOrder"
                    }
                ],
                "menu":"咨询师订单管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"咨询师",
        "tableName":"zixunshi"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"常见病症收藏管理",
                        "menuJump":"列表",
                        "tableName":"bingzhengCollection"
                    }
                ],
                "menu":"常见病症收藏管理"
            }
            ,{
                "child":[
                    
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"心理文章留言管理",
                        "menuJump":"列表",
                        "tableName":"wenzhangLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"心理文章收藏管理",
                        "menuJump":"列表",
                        "tableName":"wenzhangCollection"
                    }
                ],
                "menu":"心理文章管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"咨询师管理",
                        "menuJump":"列表",
                        "tableName":"zixunshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"咨询师留言管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"咨询师收藏管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看"
                        ],
                        "menu":"咨询师订单管理",
                        "menuJump":"列表",
                        "tableName":"zixunshiOrder"
                    }
                ],
                "menu":"咨询师管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
